// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_OF5WHsQmzXRR_yzK4Ukw-DxL_7uFrU',
    appId: '1:513445249867:web:5b3945900240f523f9dece',
    messagingSenderId: '513445249867',
    projectId: 'hivechat-8b917',
    authDomain: 'hivechat-8b917.firebaseapp.com',
    storageBucket: 'hivechat-8b917.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnyBcKfPKw7HHr1Ckjt2QhojYZadYaTJ4',
    appId: '1:513445249867:android:f752fcb733404e97f9dece',
    messagingSenderId: '513445249867',
    projectId: 'hivechat-8b917',
    storageBucket: 'hivechat-8b917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs41-nuxelHbDJdqmNbpXl1OUfCICazQk',
    appId: '1:513445249867:ios:959d063669eb5d60f9dece',
    messagingSenderId: '513445249867',
    projectId: 'hivechat-8b917',
    storageBucket: 'hivechat-8b917.firebasestorage.app',
    iosBundleId: 'com.example.hivechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs41-nuxelHbDJdqmNbpXl1OUfCICazQk',
    appId: '1:513445249867:ios:959d063669eb5d60f9dece',
    messagingSenderId: '513445249867',
    projectId: 'hivechat-8b917',
    storageBucket: 'hivechat-8b917.firebasestorage.app',
    iosBundleId: 'com.example.hivechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3_OF5WHsQmzXRR_yzK4Ukw-DxL_7uFrU',
    appId: '1:513445249867:web:3c409ff1f52a36f1f9dece',
    messagingSenderId: '513445249867',
    projectId: 'hivechat-8b917',
    authDomain: 'hivechat-8b917.firebaseapp.com',
    storageBucket: 'hivechat-8b917.firebasestorage.app',
  );
}
